inherit_gem:
  rubocop-shopify: rubocop.yml
require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - "db/migrate/*"
    - "db/seeds"
    - "config/initializers/*"
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Style/MethodCallWithArgsParentheses:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/Rails/InferredSpecType:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
