:scheduler:
  :schedule:
    process_overdue_invoices_job:
      cron: "0 0 0 * * *" # Runs once per day at midnight
      class: ProcessOverdueInvoicesJob
# *    *    *    *    *    *
# |    |    |    |    |    |
# |    |    |    |    |    +--- Day of the week (0 - 7) (Sunday=0 or 7)
# |    |    |    |    +-------- Month (1 - 12)
# |    |    |    +------------- Day of the month (1 - 31)
# |    |    +------------------ Hour (0 - 23)
# |    +----------------------- Minute (0 - 59)
# +---------------------------- Second (0 - 59)
