name: "Pull Request"
on:
  pull_request:
    branches: ["dev", "main"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
      DEFAULT_HOST: "example.local" # Changed from example.local
      DEFAULT_SUBDOMAIN: "app"
      DEFAULT_PORT: "3001"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Compile assets
        run: bundle exec rake assets:precompile

      - name: Ensure subdomain resolves in CI
        run: echo "127.0.0.1 app.example.local" | sudo tee -a /etc/hosts

      - name: Ensure subdomain resolves in CI
        run: echo "127.0.0.1 example.local" | sudo tee -a /etc/hosts

      - name: Install Chrome for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run tests
        run: bundle exec rspec spec/system/invoice/invoice_creation_spec.rb:167

      - name: Upload coverage results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Upload Capybara screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: capybara-screenshots
          path: tmp/capybara/
